server:
  port: 8082
  servlet:
    context-path: /
spring:
  application:
    name: demo-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  instance:
    # 默认每个微服务客户端的实例是他的主机名字(host name),这样的话,一个机器上只有一个该服务的实例，可以让一个机器上存在多个该微服务实例,具体配置如下
    # 详见官方文档 如下:
    # https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.2.0.RC1/reference/html/#changing-the-eureka-instance-id
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    # 这里的解释如果按照网上说的心跳间隔,会忽略掉部分内容,建议参考官方文档
    # 如下:
    # https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.2.0.RC1/reference/html/#why-is-it-so-slow-to-register-a-service
    # 租约(续约)-更新-间隔-秒(默认30)
    lease-renewal-interval-in-seconds: 30
    # 租约(续约)-过期-持续时间-秒(默认90)
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    # 注册表-获取=间隔-秒(默认30)
    registry-fetch-interval-seconds: 15
# 下面日志打印是为了验证客户端是否按照配置规则发送心跳、以及是否按照配置规则更新注册表
# 从日志中可以看到freshExecutor代表获取注册表任务、tbeatExecutor代表发送心跳间隔任务
#logging:
#  level:
#    com.netflix: debug
ribbon:
  eureka:
    enabled: false
  # 这里参数千万要注意：不要写成ReadTimeOut,参数名字写错了,配置不会生效,这个错误花了两个上午的时间
  ReadTimeout: 4000
  ConnectTimeout: 4000
  MaxAutoRetries: 0 #同一个微服务实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用

zuul:
  routes:
    clientone:
      serviceId: demo-clientone
      path: /clientOne/**
      strip-prefix: false
#      retryable: true
    clienttwo:
      serviceId: demo-clienttwo
      path: /clientTwo/**
      strip-prefix: false
# 单独配置某一个微服务的重试,如果clientTwo请求clientOne这个微服务,其中本次请求负载均衡到了clientOne1上,但是在1执行期间超时,
# 那么clientTwo就会重试,根据上面ribbon的负载均衡策略,再去请求N次(N为上面ribbon的最后两个配置)微服务
#      retryable: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
#    全局重试,pom文件中引入spring-retry
  retryable: true

#  strip-prefix: false
# 如果仅仅配置了上面的部分,直接请求网关,http://localhost:8082/clientTwo/testTwoController/testTwo,
# 不会路由到微服务demo-clienttwo上面,并且会报Load balancer does not have available server for client: demo-clienttwo错误,
# 还要配置下面的部分,具体参考官方文档,如下:
# https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.2.0.RC1/reference/html/#router-and-filter-zuul
# ribbon默认的负载均衡策略是 轮询
demo-clientone:
  listOfServers: localhost:8083,localhost:8085
demo-clienttwo:
  listOfServers: localhost:8084

# 关于hystrix的超时时间设置,基本原则为要大于ribbon的超时时间,这里的超时时间是指所有的重试次数时间加起来
# 例如:超时时间是4秒,重试一次,那么hystrix的超时时间要大于8秒,否则就会熔断,影响微服务的调用,
# 官方文档如下:
# https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.2.0.RC1/reference/html/#hystrix-timeouts-and-ribbon-clients
#hystrix:
#  command:
#    default:
#       execution:
#         timeout:
#           enabled: false
#         isolation:
#             thread:
#                timeoutInMilliseconds: 60000
#feign:
#  hystrix:
#    enabled: false


