server:
  port: 8084
  servlet:
    context-path: /clientTwo
  tomcat:
    connection-timeout: 5000
spring:
  application:
    name: demo-clientTwo
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    registry-fetch-interval-seconds: 15
# 这里配置的是微服务之间的调用超时时间
feign:
  client:
    config:
      default:
        connect-timeout: 4000
        read-timeout: 4000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000